### ISSUE TITLE
REAPER removed?

### ISSUE THREAD

**Issue by pikzen** [nodiscc/awesome-linuxaudio#50]
Hi, you just recently removed REAPER from your list. What has motivated this decision? It is still a DAW that works on Linux

**Comment by Catsvilles** [comment]
Offensive naming? How so? (Just really curious)

**Comment by joaoantoniocardoso** [comment]
22f6075 REAPER means _Rapid Environment for Audio Production, Engineering, and Recording_, it is **not** an offensive name.

**Comment by esyr** [comment]
The commit author has probably confused it with "rapist", which is kinda hilarious.

**Comment by joaoantoniocardoso** [comment]
> The commit author has probably confused it with "rapist", which is kinda hilarious.

Yeah, I should mention that _Grim Reaper_ is also a common name for the mythological character known as _Death_ and it is **not** something offensive either.

**Comment by nodiscc** [comment]
> and it is not something offensive

To who? Who decides?

I am just making fun of Cockos virtue signaling campaign, pretending to [support social change through ridiculous terminology changes](https://twitter.com/JustinFrankel/status/1272499031055437825), while buying into some braindead stupid reasoning that I won't even link here (you can find it in the twitter "thread", or whatever that is). Instead of actually doing something egalitarian (like, you know, putting some of their software under Free/Libre licenses)

Whatever, I will probably re-add it sometime. Maybe I am too easily offended by typical SV company well-thinking bullshit :) I am happy with the experiment, we got some pretty creative thinking here

> Grim Reaper

true. Who wants to think about [this dude](https://upload.wikimedia.org/wikipedia/commons/8/84/CathedralOfTrier_Skeleton.JPG) when tweaking their hi hat levels. My hamster died of corona hence I am very offended by the idea of death and all words referencing it should be removed. See where this is going?

> has probably confused it with "rapist",

This one was really well researched :) wtf...

you could release something called Hitler Multiband Compressor and I would still list it here... My point is, removing words doesn't make history and reality go away. This is just Newspeak. `Master/slave bus` is not glorifying slavery. US, fix your damn inequalities and institutional/pseudo-scientific racism instead of posturing for cheap.

You forgot [Jack the ripper](https://en.wikipedia.org/wiki/Jack_the_Ripper) by the way.

Cheers my folk. Good luck to us all in fixing our shit
