### ISSUE TITLE
Move non-free software to a separate list

### ISSUE THREAD

**Issue by Calinou** [nodiscc/awesome-linuxaudio#8]
Like https://github.com/Kickball/awesome-selfhosted did, it would make sense to move all non-free software to a separate list.

**Comment by nodiscc** [comment]
Hi, in the case of awesome-selfhosted we moved non-free software to a separate page because it brings security and privacy concerns, which are really important on server software/internet-facing machines. A lot of companies/developers would also submit paid/proprietary solutions as a form of semi-shady advertising. In the case of audio software this is not a huge concern. Most audio software on other platforms _is_ non-free, but doesn't harm security and privacy (because they don't handle personal information).

I will keep non-free software on the same page for the time being, will re-evaluate this at a later point.
